# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 523)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_cartoon = QtWidgets.QLabel(Form)
        self.login_cartoon.setMinimumSize(QtCore.QSize(580, 300))
        self.login_cartoon.setAlignment(QtCore.Qt.AlignCenter)
        self.login_cartoon.setObjectName("login_cartoon")
        self.verticalLayout_2.addWidget(self.login_cartoon)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.avatar = QtWidgets.QLabel(Form)
        self.avatar.setMinimumSize(QtCore.QSize(180, 180))
        self.avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar.setObjectName("avatar")
        self.horizontalLayout_4.addWidget(self.avatar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.UserNameEdt = QtWidgets.QLineEdit(Form)
        self.UserNameEdt.setMinimumSize(QtCore.QSize(260, 30))
        self.UserNameEdt.setObjectName("UserNameEdt")
        self.horizontalLayout.addWidget(self.UserNameEdt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.PassWdEdt = QtWidgets.QLineEdit(Form)
        self.PassWdEdt.setMinimumSize(QtCore.QSize(260, 30))
        self.PassWdEdt.setObjectName("PassWdEdt")
        self.horizontalLayout_2.addWidget(self.PassWdEdt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SignUpBtn = QtWidgets.QPushButton(Form)
        self.SignUpBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.SignUpBtn.setObjectName("SignUpBtn")
        self.horizontalLayout_3.addWidget(self.SignUpBtn)
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.SignInBtn = QtWidgets.QPushButton(Form)
        self.SignInBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.SignInBtn.setObjectName("SignInBtn")
        self.horizontalLayout_3.addWidget(self.SignInBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_cartoon.setText(_translate("Form", "动画"))
        self.avatar.setText(_translate("Form", "头像"))
        self.label.setText(_translate("Form", "UserName"))
        self.label_2.setText(_translate("Form", "Password"))
        self.SignUpBtn.setText(_translate("Form", "Sign Up"))
        self.SignInBtn.setText(_translate("Form", "Sign In"))

