# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWinUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 421)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMinimumSize(QtCore.QSize(580, 380))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setMinimumSize(QtCore.QSize(580, 380))
        self.tab1.setMaximumSize(QtCore.QSize(580, 380))
        self.tab1.setObjectName("tab1")
        self.layoutWidget = QtWidgets.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 551, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.login_userName = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_userName.setMinimumSize(QtCore.QSize(200, 40))
        self.login_userName.setObjectName("login_userName")
        self.horizontalLayout_2.addWidget(self.login_userName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.login_passwd = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_passwd.setMinimumSize(QtCore.QSize(200, 40))
        self.login_passwd.setObjectName("login_passwd")
        self.horizontalLayout_3.addWidget(self.login_passwd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loginBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.loginBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout_4.addWidget(self.loginBtn)
        self.showPasswd = QtWidgets.QCheckBox(self.layoutWidget)
        self.showPasswd.setObjectName("showPasswd")
        self.horizontalLayout_4.addWidget(self.showPasswd)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.cancelBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_4.addWidget(self.cancelBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setMinimumSize(QtCore.QSize(580, 380))
        self.tab2.setMaximumSize(QtCore.QSize(560, 360))
        self.tab2.setObjectName("tab2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab2)
        self.layoutWidget1.setGeometry(QtCore.QRect(2, 2, 551, 370))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.tab2Ver = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.tab2Ver.setContentsMargins(0, 0, 0, 0)
        self.tab2Ver.setObjectName("tab2Ver")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.SI_userName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.SI_userName.setMinimumSize(QtCore.QSize(200, 40))
        self.SI_userName.setMaximumSize(QtCore.QSize(479, 40))
        self.SI_userName.setObjectName("SI_userName")
        self.horizontalLayout_5.addWidget(self.SI_userName)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.SI_passwd = QtWidgets.QLineEdit(self.layoutWidget1)
        self.SI_passwd.setMinimumSize(QtCore.QSize(200, 40))
        self.SI_passwd.setMaximumSize(QtCore.QSize(479, 40))
        self.SI_passwd.setObjectName("SI_passwd")
        self.horizontalLayout_6.addWidget(self.SI_passwd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.SI_student_number = QtWidgets.QLineEdit(self.layoutWidget1)
        self.SI_student_number.setMinimumSize(QtCore.QSize(200, 40))
        self.SI_student_number.setMaximumSize(QtCore.QSize(479, 40))
        self.SI_student_number.setObjectName("SI_student_number")
        self.horizontalLayout_8.addWidget(self.SI_student_number)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.tab2Ver.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.SI_student_passwd = QtWidgets.QLineEdit(self.layoutWidget1)
        self.SI_student_passwd.setMinimumSize(QtCore.QSize(200, 40))
        self.SI_student_passwd.setMaximumSize(QtCore.QSize(479, 40))
        self.SI_student_passwd.setObjectName("SI_student_passwd")
        self.horizontalLayout_9.addWidget(self.SI_student_passwd)
        self.tab2Ver.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.signInBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.signInBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.signInBtn.setObjectName("signInBtn")
        self.horizontalLayout_7.addWidget(self.signInBtn)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.cancelBtn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancelBtn2.setMinimumSize(QtCore.QSize(100, 40))
        self.cancelBtn2.setObjectName("cancelBtn2")
        self.horizontalLayout_7.addWidget(self.cancelBtn2)
        self.tab2Ver.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab2, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "账号"))
        self.label_2.setText(_translate("Form", "密码"))
        self.loginBtn.setText(_translate("Form", "登录"))
        self.showPasswd.setText(_translate("Form", "显示密码"))
        self.cancelBtn.setText(_translate("Form", "离开"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Form", "登陆"))
        self.label_3.setText(_translate("Form", "账号"))
        self.label_4.setText(_translate("Form", "密码 "))
        self.label_5.setText(_translate("Form", "学号"))
        self.label_6.setText(_translate("Form", "教务处密码"))
        self.signInBtn.setText(_translate("Form", "注册"))
        self.cancelBtn2.setText(_translate("Form", "离开"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "注册"))

