# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignInPageUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(370, 356)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.avatarLabel = QtWidgets.QLabel(Dialog)
        self.avatarLabel.setMinimumSize(QtCore.QSize(180, 180))
        self.avatarLabel.setMaximumSize(QtCore.QSize(180, 180))
        self.avatarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.avatarLabel.setObjectName("avatarLabel")
        self.gridLayout.addWidget(self.avatarLabel, 0, 0, 2, 1)
        self.selfieBtn = QtWidgets.QPushButton(Dialog)
        self.selfieBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.selfieBtn.setMaximumSize(QtCore.QSize(100, 30))
        self.selfieBtn.setObjectName("selfieBtn")
        self.gridLayout.addWidget(self.selfieBtn, 0, 1, 1, 1)
        self.uploadBtn = QtWidgets.QPushButton(Dialog)
        self.uploadBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.uploadBtn.setMaximumSize(QtCore.QSize(100, 30))
        self.uploadBtn.setObjectName("uploadBtn")
        self.gridLayout.addWidget(self.uploadBtn, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setMinimumSize(QtCore.QSize(80, 20))
        self.nameLabel.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.nameEdt = QtWidgets.QLineEdit(Dialog)
        self.nameEdt.setMinimumSize(QtCore.QSize(260, 30))
        self.nameEdt.setMaximumSize(QtCore.QSize(260, 30))
        self.nameEdt.setObjectName("nameEdt")
        self.horizontalLayout.addWidget(self.nameEdt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pwLabel_1 = QtWidgets.QLabel(Dialog)
        self.pwLabel_1.setMinimumSize(QtCore.QSize(80, 20))
        self.pwLabel_1.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.pwLabel_1.setFont(font)
        self.pwLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.pwLabel_1.setObjectName("pwLabel_1")
        self.horizontalLayout_2.addWidget(self.pwLabel_1)
        self.passwdEdt_1 = QtWidgets.QLineEdit(Dialog)
        self.passwdEdt_1.setMinimumSize(QtCore.QSize(260, 30))
        self.passwdEdt_1.setMaximumSize(QtCore.QSize(260, 30))
        self.passwdEdt_1.setObjectName("passwdEdt_1")
        self.horizontalLayout_2.addWidget(self.passwdEdt_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.passwdEdt_2 = QtWidgets.QLabel(Dialog)
        self.passwdEdt_2.setMinimumSize(QtCore.QSize(80, 20))
        self.passwdEdt_2.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.passwdEdt_2.setFont(font)
        self.passwdEdt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.passwdEdt_2.setObjectName("passwdEdt_2")
        self.horizontalLayout_3.addWidget(self.passwdEdt_2)
        self.pwLabel_2 = QtWidgets.QLineEdit(Dialog)
        self.pwLabel_2.setMinimumSize(QtCore.QSize(260, 30))
        self.pwLabel_2.setMaximumSize(QtCore.QSize(260, 30))
        self.pwLabel_2.setObjectName("pwLabel_2")
        self.horizontalLayout_3.addWidget(self.pwLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.confirmBtn = QtWidgets.QPushButton(Dialog)
        self.confirmBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.confirmBtn.setMaximumSize(QtCore.QSize(100, 30))
        self.confirmBtn.setObjectName("confirmBtn")
        self.horizontalLayout_4.addWidget(self.confirmBtn)
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.cacelBtn = QtWidgets.QPushButton(Dialog)
        self.cacelBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.cacelBtn.setMaximumSize(QtCore.QSize(100, 30))
        self.cacelBtn.setObjectName("cacelBtn")
        self.horizontalLayout_4.addWidget(self.cacelBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.avatarLabel.setText(_translate("Dialog", "头像"))
        self.selfieBtn.setText(_translate("Dialog", "自拍"))
        self.uploadBtn.setText(_translate("Dialog", "本地上传"))
        self.nameLabel.setText(_translate("Dialog", "UserName"))
        self.pwLabel_1.setText(_translate("Dialog", "PassWord"))
        self.passwdEdt_2.setText(_translate("Dialog", "PassWord"))
        self.confirmBtn.setText(_translate("Dialog", "Confirm"))
        self.cacelBtn.setText(_translate("Dialog", "Cancel"))

